### PR TITLE
[DUBBO-3746] Bugfix: infinite loop in AbstractRegistry when IOException. fix #3746

### LINKED ISSUE #3746: AbstractRegistry中doSaveProperties方法如果读取的文件权限不足会进入catch块，然后重试，死循环导致cpu占用率百分百

### PR DESCRIPTION
**Pull request by kezhenxu94**
## What is the purpose of the change

resolve #3746 

When `IOException` is thrown in `org.apache.dubbo.registry.support.AbstractRegistry#doSaveProperties`, which is usually unrecoverable (permission denied, path not exists or no free disk space) it will retry infinitely, this patch tries to resolve this issue by stop retrying when `IOException` occurs.

## Brief changelog

org.apache.dubbo.registry.support.AbstractRegistry

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java [hunk 1]
```diff
@@ -174,6 +174,10 @@ public void doSaveProperties(long version) {
                 }
             }
         } catch (Throwable e) {
+            if (e instanceof IOException) { // may not be recoverable when IOException throws, give up retrying
```
Comment (ralf0131) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: Why not catch IOException directly?

**Comment by ralf0131** [comment]
What if other type of exception other than IOException is thrown, this might introduce the same issue. I think a safer way is to limit the number of time to retry.

**Comment by kezhenxu94** [comment]
> What if other type of exception other than IOException is thrown, this might introduce the same issue. I think a safer way is to limit the number of time to retry.

@ralf0131 how many times to retry? I think 3 is enough, what's your opinion?

**Comment by ralf0131** [comment]
> > What if other type of exception other than IOException is thrown, this might introduce the same issue. I think a safer way is to limit the number of time to retry.
> 
> @ralf0131 how many times to retry? I think 3 is enough, what's your opinion?

3 looks good to me.

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java [hunk 2]
```diff
@@ -60,6 +61,8 @@
     private static final char URL_SEPARATOR = ' ';
     // URL address separated regular expression for parsing the service provider URL list in the file cache
     private static final String URL_SPLIT = "\\s+";
+    // Max times to retry to save properties to local cache file
+    private static final int MAX_RETRY_TIMES_SAVE_PROPERTIES = 3;
```
Comment (carryxyh) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: I have some doubts about the retry scenario. In what scenario do we need to try again when the save file fails? Or what scenario has the first save failure, the second time may be successful?

Comment (carryxyh) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: @ralf0131 
Would u pls also check this point? Thx
:)

Comment (ralf0131) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: Er.. I'd say I am not quite sure why it is designed like this. One scenario I can think is that multiple process try to write to the same file, if other process is holding the file lock and this process might failed.  Does that sound reasonable?

Comment (carryxyh) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: Hi,huxing
Thank you for your reply.

As far as I know, if multiple processes try to write data to the same file, `acquire FD` will be called at the bottom, and this operation is usually a lock operation, so I personally think that if this happens, actually will cause queuing instead of writing failure.

But I am not very sure about this point of view. We may need a local test to ensure the rigor of the logic? 
How do u think about it?
:)

Comment (ralf0131) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: Yes, you can try it.

Comment (kezhenxu94) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: Hi @carryxyh , do you have any conclusion? If not, I think I can have a try with it. :)

**Comment by ralf0131** [comment]
Ping @carryxyh , what's your opinion on this pull request?

**Comment by carryxyh** [comment]
Sorry for coming late. @kezhenxu94 @ralf0131 

I have no more comments on this pr. After my test, multiple threads read and write to the same file will not generate exceptions and will not be out of order. But we still have to consider some other special circumstances that cause the write to fail.

I think we can merge this pr first, I will conduct further testing and submit an extra pr if I think we need to optimize it.

**Comment by carryxyh** [comment]
@kezhenxu94 
Pls help to check if `org.apache.dubbo.metadata.support.AbstractMetadataReport#doSaveProperties` has the same problem.
