### PR TITLE
[compatible] Registry compatibility #3882

### LINKED ISSUE #3882: dubbo registry extension compatibility with dubbo 2.6.x
I write a registry extension in dubbo 2.6.   Now I import it into a project that depend on dubbo2.7,  some error happened.

```
Caused by: java.lang.NoClassDefFoundError: com/alibaba/dubbo/registry/support/AbstractRegistryFactory
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_181]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_181]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_181]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_181]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_181]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_181]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_181]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_181]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:702) ~[dubbo-2.7.1.jar:2.7.1]
	... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.alibaba.dubbo.registry.support.AbstractRegistryFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_181]
	... 47 common frames omitted
```

### PR DESCRIPTION
**Pull request by cvictory**
## What is the purpose of the change

fix #3882

## Brief changelog

Registry compatibility: add some abstract class compatible.

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/incubator-dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java [hunk 1]
```diff
@@ -201,23 +201,53 @@ private void removeFailedNotified(URL url, NotifyListener listener) {
...
+    ConcurrentMap<Holder, FailedUnsubscribedTask> getFailedUnsubscribed() {
         return failedUnsubscribed;
     }
 
-    public ConcurrentMap<Holder, FailedNotifiedTask> getFailedNotified() {
+    /**
+     * remove public modifier.
+     *
+     * @return
+     * @since 2.7.2
```
Comment (cvictory) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java]: 注释，晚点我去下。

File: dubbo-compatible/src/main/java/com/alibaba/dubbo/common/utils/UrlUtils.java [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+
+import com.alibaba.dubbo.common.URL;
+
+import java.util.List;
+import java.util.Map;
+import java.util.Set;
+import java.util.stream.Collectors;
+
+/**
+ * @author cvictory ON 2019-04-17
```
Comment (Moriadry) [inline dubbo-compatible/src/main/java/com/alibaba/dubbo/common/utils/UrlUtils.java]: should we keep away from `author` in apache project?

File: dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/FailbackRegistry.java [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+
+import com.alibaba.dubbo.common.URL;
+import com.alibaba.dubbo.registry.NotifyListener;
+import com.alibaba.dubbo.registry.Registry;
+
+import java.util.List;
+import java.util.stream.Collectors;
+
+/**
+ * @author cvictory ON 2019-04-17
```
Comment (Moriadry) [inline dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/FailbackRegistry.java]: same on the above.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java [hunk 4]
```diff
@@ -48,7 +48,7 @@
     private static final Pattern INT_PATTERN = Pattern.compile("^\\d+$");
     private static final int PAD_LIMIT = 8192;
 
-    private StringUtils() {
+    protected StringUtils() {
```
[the remark this answers is not in the document]
Comment (cvictory) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: I will revert to older version.  Because some extension class used com.alibaba.dubbo.common.utils.StringUtils, I want write a class Name com.alibaba.dubbo.common.utils.StringUtils and extend the StringUtils.  Finally I found it can not fix issue.

File: dubbo-compatible/src/main/java/com/alibaba/dubbo/common/utils/UrlUtils.java (hunk 2 above)
Comment (cvictory) [reply dubbo-compatible/src/main/java/com/alibaba/dubbo/common/utils/UrlUtils.java]: Ok

File: dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/FailbackRegistry.java (hunk 3 above)
Comment (cvictory) [reply dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/FailbackRegistry.java]: ok

File: dubbo-compatible/src/main/java/com/alibaba/dubbo/common/utils/UrlUtils.java [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+import java.util.stream.Collectors;
+
+/**
+ * 2019-04-17
+ */
+@Deprecated
+public class UrlUtils {
+
+    public static URL parseURL(String address, Map<String, String> defaults) {
+        return new URL(UrlUtils.parseURL(address, defaults));
```
Comment (chickenlj) [inline dubbo-compatible/src/main/java/com/alibaba/dubbo/common/utils/UrlUtils.java]: Here should also be `org.apache.dubbo.xxx.UrlUtils `
