### PR TITLE
[Dubbo-3069]Use regular expressions to judge fix #3069

### LINKED ISSUE #3069: java.lang.NumberFormatException: For input string: ""
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: Mac OS
* Java version: Java 8

### Steps to reproduce this issue

run the following UT

```java
    @Test
    public void testConvertPrimitive() {
        Object result = ClassHelper.convertPrimitive(Integer.class, "");
    }
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

No exception is thrown.

### Actual Result

Following exception is thrown:

```
java.lang.NumberFormatException: For input string: ""

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at org.apache.dubbo.common.utils.ClassHelper.convertPrimitive(ClassHelper.java:277)
	at org.apache.dubbo.common.utils.ClassHelperTest.testConvertPrimitive(ClassHelperTest.java:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### Improvement

1. Throwing exception is expensive, return null if input String is null or ""
2. Add more test cases to this method.

### PR DESCRIPTION
**Pull request by CrazyHZM**
## What is the purpose of the change
Use regular expressions to judge
fix #3069

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java [hunk 1]
```diff
@@ -265,26 +264,33 @@ public static boolean isPrimitive(Class<?> type) {
     }
 
     public static Object convertPrimitive(Class<?> type, String value) {
-        if (type == char.class || type == Character.class) {
+        if (value == null) {
```
Comment (khanimteyaz) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: I think 
```
if(value==null || !isNumber(value)) { 
    return null;
}
```

should be good enough for all these, is it it?

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: If you do this, values ​​that are not numeric will also return null. 
for example `value = “true”`

Comment (khanimteyaz) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: ok

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java [hunk 2]
```diff
@@ -265,26 +264,33 @@ public static boolean isPrimitive(Class<?> type) {
...
+            return isNumber(value) ? Float.valueOf(value) : null;
         } else if (type == double.class || type == Double.class) {
-            return Double.valueOf(value);
+            return isNumber(value) ? Double.valueOf(value) : null;
         }
         return value;
     }
 
+    public static boolean isNumber(String str) {
+        String reg = "^[0-9]+(.[0-9]+)?$";
```
Comment (lixiaojiee) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: Personally, I think that variables like this can be moved into Constants class.

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: Thanks, this is a good idea. I will modify it.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java [hunk 3]
```diff
@@ -265,26 +266,38 @@ public static boolean isPrimitive(Class<?> type) {
...
-        if (type == char.class || type == Character.class) {
+        if (value == null) {
+            return null;
+        } else if (type == char.class || type == Character.class) {
             return value.length() > 0 ? value.charAt(0) : '\0';
         } else if (type == boolean.class || type == Boolean.class) {
             return Boolean.valueOf(value);
         } else if (type == byte.class || type == Byte.class) {
-            return Byte.valueOf(value);
+            return isNumber(value) ? Byte.valueOf(value) : null;
```
Comment (ralf0131) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: I don't think it is a good way to use regular express to check whether it is a number before doing the conversion, which is quite expensive. Please take a look at org.apache.dubbo.common.utils.StringUtils#isNumeric()

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: This method cannot exclude numbers with decimal points.

Comment (ralf0131) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: Maybe you can enhance it based on the logic provided in `org.apache.dubbo.common.utils.StringUtils#isNumeric()`

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: thanks,I will modify it.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java [hunk 4]
```diff
@@ -491,6 +490,25 @@ public static boolean isNumeric(String str) {
         return true;
     }
 
+    public static boolean isNumber(String str) {
```
Comment (ralf0131) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: How about something like this:

```java
public static boolean isNumeric(String str, boolean allowDot) {
        if (str == null) {
            return false;
        }
        int sz = str.length();
        for (int i = 0; i < sz; i++) {
            if ((!allowDot && str.charAt(i) == '.') || !Character.isDigit(str.charAt(i))) {
                return false;
            }
        }
        return true;
    }
```

Not tested yet. Just for your information. In this way we can unify the logic into one method.
And call isNumeric(value, true) from ClassHelper.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java [hunk 5]
```diff
@@ -265,26 +265,29 @@ public static boolean isPrimitive(Class<?> type) {
...
-        if (type == char.class || type == Character.class) {
+        if (value == null) {
+            return null;
+        } else if (type == char.class || type == Character.class) {
             return value.length() > 0 ? value.charAt(0) : '\0';
         } else if (type == boolean.class || type == Boolean.class) {
             return Boolean.valueOf(value);
         } else if (type == byte.class || type == Byte.class) {
-            return Byte.valueOf(value);
+            return StringUtils.isNumber(value) ? Byte.valueOf(value) : null;
```
Comment (ralf0131) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: No need to call `StringUtils.isNumber(value)` every time. We can put it in front.

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: It may not be these eight types, if it is placed in front, exporterMethodConfigUrlTest will not pass

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java (hunk 4 above)
Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: I have modified it.

**Comment by CrazyHZM** [comment]
@ralf0131 Hi,pls review my latest changes

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java (hunk 2 above)
Comment (khanimteyaz) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: @CrazyHZM are you planning to move this to Constants file?

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: > @CrazyHZM are you planning to move this to Constants file?
I have removed it since the last change.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java [hunk 6]
```diff
@@ -478,10 +477,23 @@ public static boolean isContains(String[] values, String value) {
         return false;
     }
 
-    public static boolean isNumeric(String str) {
-        if (str == null) {
+    public static boolean isNumeric(String str, boolean allowDot) {
+        if (str == null || str.isEmpty()) {
             return false;
         }
+        if (allowDot) {
```
Comment (satansk) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: Can handle something like ".1" or not?

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: StringUtils.isNumeric(left, false) && StringUtils.isNumeric(right, false)

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: That's no problem, it will go to the logic below and it will return false.

Comment (satansk) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: `Double.valueOf(".1"))` will produce 0.1, so I personally think it's better to support this pattern.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java [hunk 7]
```diff
@@ -265,26 +265,29 @@ public static boolean isPrimitive(Class<?> type) {
...
-        if (type == char.class || type == Character.class) {
+        if (value == null) {
+            return null;
+        } else if (type == char.class || type == Character.class) {
             return value.length() > 0 ? value.charAt(0) : '\0';
         } else if (type == boolean.class || type == Boolean.class) {
             return Boolean.valueOf(value);
         } else if (type == byte.class || type == Byte.class) {
-            return Byte.valueOf(value);
+            return StringUtils.isNumeric(value, false) ? Byte.valueOf(value) : null;
```
Comment (beiwei30) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: I am not persuaded that 'StringUtils.isNumeric()' is required here. In my opinion, JDK has already offered the nice API and we should stick to it. What we need to do is to catch **NumberFormatException** and return 'null' if necessary.

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java]: I think this is good, but I think the function enhancement of `StringUtils.isNumeric()` is not necessary to delete it. What do you think?

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java (hunk 6 above)
Comment (ralf0131) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: Hi,

I am not a fan of recursive call, especially for such a small function. I think this can be implemented by at most 2 for loops.

Can you replace it by a non-recursive call?

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: I have modified it.

Comment (ralf0131) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: Hi, 

How about this:

```java
public static boolean isNumeric(String str, boolean allowDot) {
        if (str == null || str.isEmpty()) {
            return false;
        }
        int dotCount = 0;
        for (int i = 0; i < str.length(); i++) {
            if (str.charAt(i) == '.') {
                if (allowDot && dotCount == 0) {
                    dotCount++;
                    continue;
                } else {
                    return false;
                }
            }
            if (!Character.isDigit(str.charAt(i))) {
                return false;
            }
        }
        return true;
    }
```

This only need 1 loop. And also support something like "1." as a numeric.

```
jshell> Double.valueOf("1.")
$1 ==> 1.0
```

I also add some more unit test

```java
assertThat(StringUtils.isNumeric("123.3.3", true), is(false));
assertThat(StringUtils.isNumeric("123.", true), is(true));
```

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: So is there a support for “.1”?

Comment (ralf0131) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: Definitely yes. You can add it to the UT.

Comment (CrazyHZM) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java]: do it.
