### PR TITLE
[#3817]Support Redis cluster in Metadata Report

### LINKED ISSUE #3817: redis 元数据中心，目前不支持集群？
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2-SNAPSHOT
* Operating System version: windows1
* Java version: 1.8

### Steps to reproduce this issue
```java
public class RedisMetadataReport extends AbstractMetadataReport {

    private final static Logger logger = LoggerFactory.getLogger(RedisMetadataReport.class);

    final JedisPool pool;

    public RedisMetadataReport(URL url) {
        super(url);
        pool = new JedisPool(new JedisPoolConfig(), url.getHost(), url.getPort());
    }
}
```
I see the construct method used `JedisPool`, 
**if cluster ，how should  do？**

### PR DESCRIPTION
**Pull request by cvictory**
## What is the purpose of the change

Fix #3817,  for suport redis cluster in meatadata report.

## Brief changelog

Introduce Redis Cluster.

Reference: 

https://redis.io/topics/cluster-spec  

https://redis.io/topics/cluster-tutorial

https://github.com/xetorthio/jedis#jedis-cluster

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by cvictory** [comment]
I donot find  how to start redis cluster in embed redis.  

I will try my best to add some test.

**Comment by ralf0131** [comment]
Hi, sorry but could you resolve the conflict first?

File: dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java [hunk 1]
```diff
@@ -16,28 +16,46 @@
...
 
-    final JedisPool pool;
+    JedisPool pool;
+    Set<HostAndPort> jedisClusterNodes;
+
 
     public RedisMetadataReport(URL url) {
         super(url);
-        pool = new JedisPool(new JedisPoolConfig(), url.getHost(), url.getPort());
+        if (url.getParameter(Constants.CLUSTER_KEY, false)) {
```
Comment (chickenlj) [inline dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java]: `CLUSTER_KEY` is also used for other purposes http://dubbo.apache.org/zh-cn/docs/user/demos/fault-tolerent-strategy.html.

You need to add a prefix for `CLUSTER_KEY` key in this module to avoid overridden with the same key from other modules.

Comment (chickenlj) [reply dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java]: Sorry, I forgot the url passed in is generated from MetadataConfig.

Comment (cvictory) [reply dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java]: Ok, I just reuse this key in metadataConfig.
