### PR TITLE
[Dubbo-3361] Make DubboAppender extends from FileAppender

### LINKED ISSUE #3361: Should limit console output of unit test
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master branch
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

Travis-cli has a 4MB hard limit of log size [1].
Currently, our Travis log[2] is about 3.98MB, we are almost there.
We can reduce some trivial log in the console output, but keep a full log in the local file.

For example, test case `org.apache.dubbo.rpc.validation.ValidationTest` eats about 1.3MB in travis log. We can start from here.

[1]. https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded
[2]. https://api.travis-ci.org/v3/job/484750418/log.txt

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

### PR DESCRIPTION
**Pull request by biyuhao**
## What is the purpose of the change
limit console output of unit test
Fix #3361

## Brief changelog

Make DubboAppender extends from FileAppender
Tweak unit test log path

## Verifying this change

UT pass and Travis log size drop to about 1.5MB
for local environment there should be a `dubbo.log` file contains unit test log.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by biyuhao** [comment]
travis log for jdk8 is about `1.52MB` https://api.travis-ci.org/v3/job/485782659/log.txt
travis log for jdk11 is ablout `1.53 MB` https://api.travis-ci.org/v3/job/485782658/log.txt

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/DubboAppender.java [hunk 1]
```diff
@@ -16,13 +16,18 @@
...
 
 import java.util.ArrayList;
 import java.util.List;
 
-public class DubboAppender extends ConsoleAppender {
+public class DubboAppender extends FileAppender {
+
+    public DubboAppender() {
+        super();
+        setFile("dubbo.log");
```
Comment (khanimteyaz) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/DubboAppender.java]: should we not read this from constant or from some config?

**Comment by biyuhao** [comment]
> How about in .travis.yml, use linux pipe to redirect to file:
> 
> ```
> ./mvnw clean test xxx xxx  > dubbo.log 2>&1
> ```
> And after failure, using the same `tail -n 1000 dubbo.log`

I'll try this one in my repo later.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/DubboAppender.java (hunk 1 above)
Comment (biyuhao) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/DubboAppender.java]: This will initialize output file with a default value.
Usually, we will overwrite it in `log4j.xml`, in this PR we use `<param name="File" value="../../dubbo.log"/>`

**Comment by biyuhao** [comment]
> > How about in .travis.yml, use linux pipe to redirect to file:
> > ```
> > ./mvnw clean test xxx xxx  > dubbo.log 2>&1
> > ```
> > And after failure, using the same `tail -n 1000 dubbo.log`
> 
> I'll try this one in my repo later.

Seems it's not working.
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

https://api.travis-ci.org/v3/job/486256538/log.txt

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/DubboAppender.java (hunk 1 above)
Comment (ralf0131) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/DubboAppender.java]: If that is the case, it is better to add a 

```java
private static final String DEFAULT_FILE_NAME = "dubbo.log";
```
