### PR TITLE
[Dubbo-2423] Multicast demo fails with message "Can't assign requested address".

### LINKED ISSUE #2423: Multicast demo fails with message "Can't assign requested address"
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master branch
* Operating System version: macOS 10.13.6
* Java version: 1.8

### Step to reproduce this issue

1. start the provider demo

### Expected Result

Provider start success.

### Actual Result

Provider start failed.

If there is an exception, please attach the exception trace:

```
Caused by: java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at org.apache.dubbo.registry.multicast.MulticastRegistry.<init>(MulticastRegistry.java:91)
	... 24 more
```

If I add vm args `-Djava.net.preferIPv4Stack=true`, everything works fine.

### PR DESCRIPTION
**Pull request by chickenlj**
## What is the purpose of the change

Fixes #2423

## Brief changelog

MulticastRegistry
NetUtils

## Verifying this change

Run demos using the multicast registry.
Check MulticastRegistryTest UT

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java [hunk 1]
```diff
@@ -82,13 +82,11 @@ public MulticastRegistry(URL url) {
         try {
             multicastAddress = InetAddress.getByName(url.getHost());
             if (!multicastAddress.isMulticastAddress()) {
-                throw new IllegalArgumentException("Invalid multicast address " + url.getHost() +
-                        ", ipv4 multicast address scope: 224.0.0.0 - 239.255.255.255.");
+                throw new IllegalArgumentException("Invalid multicast address " + url.getHost() + ", ipv4 multicast address scope: 224.0.0.0 - 239.255.255.255.");
```
[the remark this answers is not in the document]
Comment (chickenlj) [reply dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java]: I think we should also include ipv6 hint in the error message.

File: dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java [hunk 2]
```diff
@@ -220,4 +221,40 @@ public void testCustomedPort() {
...
+                NetUtils.setInterface(multicastSocket, multicastAddress);
+                multicastSocket.joinGroup(multicastAddress);
+            } finally {
+                if (multicastSocket != null) {
+                    multicastSocket.close();
+                }
+            }
+
+            // multicast ipv6 address,
+            /*try {
```
Comment (htynkn) [inline dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java]: why those code are removed? are we still need `-Djava.net.preferIPv4Stack=true` after this change are made?

Comment (chickenlj) [reply dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java]: No, only because this UT can not pass in travis with ipv6 address. I think the travis host does not have an interface supporting ipv6.

**Comment by beiwei30** [comment]
let's merge it, I will follow up with the error message.
