### PR TITLE
[DUBBO-2988] Unrecognized the other provider

### LINKED ISSUE #2988: [Dubbo - telnet] Unrecognized the other provider
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

## Environment
- Dubbo version: 2.7.0+
- Operating System version: mac
- Java version: 1.8
## Steps to reproduce this issue
Assume that there is an interface below：
``` java
package org.apache.dubbo.demo;
public interface DemoService {
    String sayHello(String name);
}

package org.apache.dubbo.demo.provider;
import org.apache.dubbo.demo.DemoService;
public class DemoAService implements DemoService {
    @Override
    public String sayHello(String name) {
        return "Hello " + name + ", response from provider: " + this.getClass().getSimpleName();
    }
}

package org.apache.dubbo.demo.provider;
import org.apache.dubbo.demo.DemoService;
public class DemoBService implements DemoService {
    @Override
    public String sayHello(String name) {
        return "Hello " + name + ", response from provider: " + this.getClass().getSimpleName();
    }
}
```
dubbo-demo-provider.xml:
```
    <!-- service implementation, as same as regular local bean -->
    <bean id="demoAService" class="org.apache.dubbo.demo.provider.DemoAService"/>

    <!-- declare the service interface to be exported -->
    <dubbo:service interface="org.apache.dubbo.demo.DemoService" ref="demoAService" group="demoA"/>

    <!-- service implementation, as same as regular local bean -->
    <bean id="demoBService" class="org.apache.dubbo.demo.provider.DemoBService"/>

    <!-- declare the service interface to be exported -->
    <dubbo:service interface="org.apache.dubbo.demo.DemoService" ref="demoBService" group="demoB"/>
```
## Start telnet call service：
``` shell
incubator-dubbo yeling$ telnet localhost 20880
dubbo>ls
org.apache.dubbo.demo.DemoService
org.apache.dubbo.demo.DemoService
dubbo>invoke org.apache.dubbo.demo.DemoService.sayHello("china") 
"Hello china, response from provider: DemoAService"
```
- Always only call the provider DemoAService，There's no way I can invoke to DemoBService.

### PR DESCRIPTION
**Pull request by beiwei30**
## What is the purpose of the change

fix #2988 

## Brief changelog

1. start to honor both 'group' and 'version'
2. git rid of relying on Dubbo protocol's exporter, instead, use injvm invoker and application model.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-demo/dubbo-demo-provider/src/main/java/org/apache/dubbo/demo/provider/ServiceA.java
dubbo-demo/dubbo-demo-provider/src/main/java/org/apache/dubbo/demo/provider/ServiceB.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java
dubbo-rpc/dubbo-rpc-dubbo/pom.xml
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ImplicitCallBackTest.java

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java [hunk 1]
```diff
@@ -1,535 +1,535 @@
-/*
```
Comment (jasonjoo2010) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java]: I think we should avoid unnecessary code format to show the difference clearly.

Comment (khanimteyaz) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java]: yes agree.

File: dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java [hunk 2]
```diff
@@ -58,7 +57,7 @@ public String listProvider() {
 
         //Content
         for (ProviderModel providerModel : ProviderModelList) {
-            tTable.addRow(providerModel.getServiceName(), isReg(providerModel.getServiceName()) ? "Y" : "N");
+            tTable.addRow(providerModel.getServiceName(), isRegistered(providerModel.getServiceName()) ? "Y" : "N");
```
Comment (khanimteyaz) [inline dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java]: Better to define a constant for "Y" and "N".

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java [hunk 3]
```diff
@@ -92,4 +92,29 @@ public static void registerConsumer(Invoker invoker, URL registryUrl, URL consum
         return invokers;
     }
 
+    public static boolean isRegistered(String serviceUniqueName) {
+        Set<ProviderInvokerWrapper> providerInvokerWrapperSet = ProviderConsumerRegTable.getProviderInvoker(serviceUniqueName);
+        for (ProviderInvokerWrapper providerInvokerWrapper : providerInvokerWrapperSet) {
```
Comment (khanimteyaz) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java]: can be rewritten as 
return providerInvokerWrapperSet.stream().anyMatch(ProviderInvokerWrapper::isReg);

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java [hunk 4]
```diff
@@ -92,4 +92,29 @@ public static void registerConsumer(Invoker invoker, URL registryUrl, URL consum
...
+                return true;
+            }
+        }
+
+        return false;
+    }
+
+    public static int getConsumerAddressNum(String serviceUniqueName) {
+        int count = 0;
+        Set<ConsumerInvokerWrapper> providerInvokerWrapperSet = ProviderConsumerRegTable.getConsumerInvoker(serviceUniqueName);
```
Comment (khanimteyaz) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java]: can be replace by 

return providerInvokerWrapperSet.stream()
                .map(piw->piw.getRegistryDirectory().getUrlInvokerMap())
                .filter(Objects::nonNull)
                .mapToInt(Map::size).sum();

File: dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java [hunk 5]
```diff
@@ -147,8 +147,8 @@ protected void initServConf() {
         regConfForProvider = new RegistryConfig();
         regConfForService = new RegistryConfig();
         provConf = new ProviderConfig();
-        protoConfForProvider = new ProtocolConfig();
-        protoConfForService = new ProtocolConfig();
+        protoConfForProvider = new ProtocolConfig("mockprotocol");
```
[the remark this answers is not in the document]
Comment (beiwei30) [reply dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java]: let leave it as is :)

File: dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java (hunk 2 above)
Comment (beiwei30) [reply dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java]: let's leave it as is.

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java (hunk 4 above)
Comment (beiwei30) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java]: done

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java (hunk 1 above)
Comment (beiwei30) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java]: fixed

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java (hunk 3 above)
Comment (beiwei30) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java]: done.

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java (hunk 4 above)
Comment (beiwei30) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java]: done

File: dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java [hunk 6]
```diff
@@ -34,7 +34,7 @@ public void testInjvm() throws Exception {
         registry.setAddress("multicast://224.5.6.7:1234");
 
         ProtocolConfig protocol = new ProtocolConfig();
-        protocol.setName("dubbo");
+        protocol.setName("mockprotocol");
```
Comment (khanimteyaz) [inline dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java]: Should we create a test constant for this, as we might be using it many places. It will be easier to  change in case in future if have to do.

File: dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java [hunk 7]
```diff
@@ -69,7 +69,7 @@ public void testReferenceRetry() {
         RegistryConfig registry = new RegistryConfig();
         registry.setAddress("multicast://224.5.6.7:1234");
         ProtocolConfig protocol = new ProtocolConfig();
-        protocol.setName("dubbo");
+        protocol.setName("mockprotocol");
```
Comment (khanimteyaz) [inline dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java]: same as above.

File: dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (khanimteyaz) [reply dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java]: ok

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java (hunk 4 above)
Comment (khanimteyaz) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java]: Thanks.

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java [hunk 8]
```diff
@@ -72,4 +72,12 @@ public static void initProviderModel(String serviceName, ProviderModel providerM
             LOGGER.warn("Already register the same:" + serviceName);
         }
     }
+
+    /**
+     * For unit test
+     */
+    public static void reset() {
+        providedServices.clear();
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java]: I beleive providedServices and consumedServices would be never null here?

Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java]: Sorry my bad, it is initialize in this class while it is created. Plz ignore this comment 😄

Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java]: Just one thought, as you are indicating it is only for unit test, should we mark access specifier as protected. Which could help to use it more knowingly. This is just an thought.

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java [hunk 9]
```diff
@@ -29,11 +29,13 @@
...
 
     private final Map<Method, ConsumerMethodModel> methodModels = new IdentityHashMap<Method, ConsumerMethodModel>();
 
-    public ConsumerModel(String serviceName, Object proxyObject, Method[] methods, Map<String, Object> attributes) {
+    public ConsumerModel(String serviceName, Class<?> serviceInterfaceClass, Object proxyObject, Method[] methods, Map<String, Object> attributes) {
         this.serviceName = serviceName;
+        this.serviceInterfaceClass = serviceInterfaceClass;
         this.proxyObject = proxyObject;
 
         if (proxyObject != null) {
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java]: Is methods and attributes are optional and can be consider my this class only if proxyObject not null? If this is the case then can we have two constructor one with only service and another one with all the parameters?

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java [hunk 10]
```diff
@@ -119,26 +120,30 @@ private static boolean isMatch(Class<?>[] types, List<Object> args, Class<?>[] p
...
         if (message == null || message.length() == 0) {
-            return "Please input method name, eg: \r\ninvoke xxxMethod(1234, \"abcd\", {\"prop\" : \"value\"})\r\ninvoke XxxService.xxxMethod(1234, \"abcd\", {\"prop\" : \"value\"})\r\ninvoke com.xxx.XxxService.xxxMethod(1234, \"abcd\", {\"prop\" : \"value\"})";
+            return "Please input method name, eg: \r\ninvoke xxxMethod(1234, \"abcd\", {\"prop\" : \"value\"})\r\n" +
+                    "invoke XxxService.xxxMethod(1234, \"abcd\", {\"prop\" : \"value\"})\r\n" +
+                    "invoke com.xxx.XxxService.xxxMethod(1234, \"abcd\", {\"prop\" : \"value\"})";
         }
+
         StringBuilder buf = new StringBuilder();
         String service = (String) channel.getAttribute(ChangeTelnetHandler.SERVICE_KEY);
         if (service != null && service.length() > 0) {
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: Can be repalce with 
```
if(!StringUtils.isEmpty(service)) {
  buf.append("Use default service ").append(service).append(".\r\n");
}
```

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java [hunk 11]
```diff
@@ -147,76 +152,81 @@ public String telnet(Channel channel, String message) {
...
-                if (service.equals(exporter.getInvoker().getInterface().getSimpleName())
-                        || service.equals(exporter.getInvoker().getInterface().getName())
-                        || service.equals(exporter.getInvoker().getUrl().getPath())) {
-                    invokeMethod = findMethod(exporter, method, list, paramClasses);
-                    invoker = exporter.getInvoker();
-                    break;
-                }
+        ProviderModel selectedProvider = null;
+        for (ProviderModel provider : ApplicationModel.allProviderModels()) {
+            if (provider.getServiceName().equalsIgnoreCase(service)
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: Should we refactor this to a another method something like 
if (isServiceMatch(provider,service) {
  -- existing code ---
}
public static boolean isServiceMatch( ProviderModel provider,String service) {
   return StringUtils.isEmpty(service) 
              ||provider.getServiceName().equalsIgnoreCase(service)
              ||provider.getServiceName().equalsIgnoreCase(service)
              ||provider.getServiceInterfaceClass().getSimpleName().equalsIgnoreCase(service)
              ||provider.getServiceInterfaceClass().getName().equalsIgnoreCase(service)
}

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java (hunk 8 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java]: It cannot be protected, since it's used in telnet's unit test.

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java (hunk 9 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java]: I am afraid I don't fully understand, could you pls. rephrase your concern?

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java (hunk 10 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: done.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java (hunk 11 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: done.

File: dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java (hunk 6 above)
Comment (beiwei30) [reply dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java]: let's revisit this when we enhance unit test in config-api. In my opinion, config-api's unit test needs to clean up:

1. as you mentioned, not only 'mock protocol' but also other constants are needed to defined as constants.
2. there are some test cases depends on other module which may lead to cycle dependency in the future, for example: 'dubbo-registry-multicast' should not be used by 'dubbo-config-api'.

In this pull request, I solved some of cycle dependencies when I start to use 'dubbo-config-api' in 'dubbo-rpc-dubbo'. We should address others in another delegated change.

File: dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java (hunk 7 above)
Comment (beiwei30) [reply dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java]: ditto

File: dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java (hunk 6 above)
Comment (khanimteyaz) [reply dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java]: Agree with you. May be once this PR is merged I could take this cleanup part.

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java (hunk 8 above)
Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java]: ok.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java [hunk 12]
```diff
@@ -119,26 +120,30 @@ private static boolean isMatch(Class<?>[] types, List<Object> args, Class<?>[] p
     @SuppressWarnings("unchecked")
     public String telnet(Channel channel, String message) {
         if (message == null || message.length() == 0) {
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: Can be change to 
`if(!StringUtils.isEmpty(message))`

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java [hunk 13]
```diff
@@ -46,55 +51,107 @@ public String telnet(Channel channel, String message) {
...
+        }
+        return buf.toString();
+    }
+
+    private void printAllServices(StringBuilder buf, boolean detail) {
+        printAllProvidedServices(buf, detail);
+        printAllReferredServices(buf, detail);
+    }
+
+    private void printAllProvidedServices(StringBuilder buf, boolean detail) {
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: Can be simplified to 
`private void printAllProvidedServices(StringBuilder buf, boolean detail) {
        if(!ApplicationModel.allProviderModels().isEmpty()) {
            buf.append("PROVIDER:\r\n");
        }
        for (ProviderModel provider : ApplicationModel.allProviderModels()) {
            buf.append(provider.getServiceName());
            if (detail) {
                buf.append(" -> ");
                buf.append(" published: ");
                buf.append(isRegistered(provider.getServiceName()) ? "Y" : "N");
            }
            buf.append("\r\n");
        }
    }`

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java [hunk 14]
```diff
@@ -46,55 +51,107 @@ public String telnet(Channel channel, String message) {
...
+                buf.append(" -> ");
+                buf.append(" published: ");
+                buf.append(isRegistered(provider.getServiceName()) ? "Y" : "N");
+            }
+            buf.append("\r\n");
+        }
+    }
+
+    private void printAllReferredServices(StringBuilder buf, boolean detail) {
+        boolean printHeader = true;
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: can be done same as above approach

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java [hunk 15]
```diff
@@ -46,55 +51,107 @@ public String telnet(Channel channel, String message) {
...
+    }
+
+    private void printSpecifiedService(String service, StringBuilder buf, boolean detail) {
+        printSpecifiedProvidedService(service, buf, detail);
+        printSpecifiedReferredService(service, buf, detail);
+    }
+
+    private void printSpecifiedProvidedService(String service, StringBuilder buf, boolean detail) {
+        for (ProviderModel provider : ApplicationModel.allProviderModels()) {
+            if (service.equalsIgnoreCase(provider.getServiceName())
```
Comment (khanimteyaz) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: can be change to same above one of the example
`if(isServiceMatch(service,provider)) {
buf.append(provider.getServiceName()).append(" (as provider):\r\n");
for (ProviderMethodModel method : provider.getAllMethods()) {
printMethod(method.getMethod(), buf, detail);
}
}`

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java [hunk 16]
```diff
@@ -46,55 +51,107 @@ public String telnet(Channel channel, String message) {
...
                     if (service != null && service.length() > 0) {
-                        return "Invaild parameter " + part;
+                        return "Invalid parameter " + part;
                     }
                     service = part;
                 }
             }
         } else {
             service = (String) channel.getAttribute(ChangeTelnetHandler.SERVICE_KEY);
             if (service != null && service.length() > 0) {
```
[the remark this answers is not in the document]
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: done.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java [hunk 17]
```diff
@@ -46,55 +51,107 @@ public String telnet(Channel channel, String message) {
...
-                buf.append("Use default service " + service + ".\r\n");
+                buf.append("Use default service ").append(service).append(".\r\n");
             }
         }
+
         if (service == null || service.length() == 0) {
```
[the remark this answers is not in the document]
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: done.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java (hunk 12 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: done.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java (hunk 13 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: done.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java (hunk 15 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: done.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java (hunk 14 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: done.

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java (hunk 9 above)
Comment (beiwei30) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java]: In fact, `if (proxyObject != null)` is a defensive programming. In Dubbo, proxyObject should not be null and will not be null. 

I guess we should change it to `assert` or `throw IllegelArgumentException`, would you mind take care of this in other change? 

This change contains too much already, in my opinion.

Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java]: Sure.

**Comment by beiwei30** [comment]
since there's no further comments, I will merge this pull request. @khanimteyaz you can continue your work based on it.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java [hunk 18]
```diff
@@ -147,77 +152,86 @@ public String telnet(Channel channel, String message) {
...
-                    RpcContext.getContext().setLocalAddress(channel.getLocalAddress()).setRemoteAddress(channel.getRemoteAddress());
+                    Object[] array = realize(list.toArray(), invokeMethod.getParameterTypes(),
+                            invokeMethod.getGenericParameterTypes());
+                    getContext().setLocalAddress(channel.getLocalAddress()).setRemoteAddress(channel.getRemoteAddress());
                     long start = System.currentTimeMillis();
-                    Object result = invoker.invoke(new RpcInvocation(invokeMethod, array)).recreate();
+                    RpcResult result = new RpcResult();
+                    try {
+                        Object o = invokeMethod.invoke(selectedProvider.getServiceInstance(), array);
+                        result.setValue(o);
```
Comment (chickenlj) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: I doubt that invoking the underlying service instance directly bypassing Dubbo's proxy will make this `invoke` command meaningless. For a reading service, the result may be qualified as a reflection of that it will behave in production; for a writing service, the side effects may be not predictable

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java [hunk 19]
```diff
@@ -54,47 +60,95 @@ public String telnet(Channel channel, String message) {
...
-            }
+
+        if (StringUtils.isEmpty(service)) {
+            printAllServices(buf, detail);
         } else {
-            Invoker<?> invoker = null;
-            for (Exporter<?> exporter : DubboProtocol.getDubboProtocol().getExporters()) {
-                if (service.equals(exporter.getInvoker().getInterface().getSimpleName())
-                        || service.equals(exporter.getInvoker().getInterface().getName())
-                        || service.equals(exporter.getInvoker().getUrl().getPath())) {
```
Comment (chickenlj) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: `service.equals(exporter.getInvoker().getUrl().getPath())` 
This condition will lost in the new implementation while the Model concept used only takes `group/service:version` into account. I am a little confused about the relation between `path` and `group/service:version` at this moment, but I think we should be careful before we can think of them clearly enough.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java (hunk 18 above)
Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: @chickenlj would be possible to explain this in a bit more details (you might have already explained it, but for the shake of mine understanding it would great if you can again)

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java (hunk 19 above)
Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java]: Yes agree that for changes we should be thought full. In this case what approach we could take to make it better. If you could guide, we would make change to enhance it?

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java (hunk 18 above)
Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: @carryxyh . Got it. Thanks for expplaing it to me. What you saying is make sense and I think we allow to use the actual call path instead of by pass.

Comment (khanimteyaz) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java]: @carryxyh I have created an issue [3059](https://github.com/apache/incubator-dubbo/issues/3059) for the same which we can use as a reffrence to work on.
