### PR TITLE
fix telnet not work in some scene (#4007)

### LINKED ISSUE #4007: telnet can't work when parameter has no nullary constructor and some fields is primitive
### Environment

* Dubbo version: 2.6.0
* Operating System version: macOS 10.14.3
* Java version: 1.8.0_201

### Steps to reproduce this issue

1. create a class has no nullary constructor and some fields is primitive
```java
public class User implements Serializable {
    private static final long serialVersionUID = -467269449632818122L;
    private int age;
    private String name;
    public User(int age, String name) {
        this.age = age;
        this.name = name;
    }
}
```
2. create new method in DemoService
```java
public interface DemoService {
    String sayHello(User user);
}
```
3. telnet and invoke this method
```
invoke sayHello({"age":1,"name":"String","class":"User"})
```

### Expected Result

can invoke successfully

### Actual Result

throw exception java.lang.IllegalArgumentException

If there is an exception, please attach the exception trace:

```java
java.lang.IllegalArgumentException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.alibaba.dubbo.common.utils.PojoUtils.newInstance(PojoUtils.java:527)
        at com.alibaba.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:436)
        at com.alibaba.dubbo.common.utils.PojoUtils.realize(PojoUtils.java:196)
        at com.alibaba.dubbo.common.utils.PojoUtils.realize(PojoUtils.java:86)
        at com.alibaba.dubbo.rpc.protocol.dubbo.telnet.InvokeTelnetHandler.telnet(InvokeTelnetHandler.java:138)
        at com.alibaba.dubbo.remoting.telnet.support.TelnetHandlerAdapter.telnet(TelnetHandlerAdapter.java:52)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by fibbery**
## What is the purpose of the change

fix #4007

## Brief changelog

XXXXX

## Verifying this change

org.apache.dubbo.common.utils.PojoUtilsTest#test_has_no_nullary_constructor_pojo()

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/incubator-dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java [hunk 1]
```diff
@@ -541,6 +549,26 @@ private static Object newInstance(Class<?> cls) {
         }
     }
 
+    /**
+     * return init value when type is primitive
+     * @param parameterType
+     * @return
+     */
+    private static Object getPrimitiveDefaultValue(Class<?> parameterType) {
+        if (parameterType.getName().equals("int") || parameterType.getName().equals("short")
```
Comment (ralf0131) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java]: java.lang.Class provides a method call isPrimitive(). I think it can be used here:

```
if (parameterType is char) return Character.MINVALUE;
if (parameterType is primitive) return 0;
return null
```

Does that look simpler?

Comment (fibbery) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java]: yes , make this method become simple and general

**Comment by ralf0131** [comment]
Hey, it looks like the UT is failing, could you please take a look?

**Comment by fibbery** [comment]
@ralf0131 
I fix some codestyle, but UT still can't work.
I can't find the fail message

**Comment by ralf0131** [comment]
It failed because the license check. I think it is due to that you added a new java file but no have ASF license header.

```
Rat check: Summary over all files. Unapproved: 1, unknown: 1, generated: 0, approved: 302 licenses.
```

**Comment by fibbery** [comment]
@ralf0131 
can you help me? 
I can't fix this build error

**Comment by fibbery** [comment]
```java
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.672 s <<< FAILURE! - in org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest
[ERROR] testStoreProvider  Time elapsed: 2.895 s  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest.testStoreProvider(EtcdMetadataReportTest.java:85)
```
why occur only in openjdk11 @ralf0131
